w4 png2src --rust player.png > out/player.rs
w4 png2src --rust lie.png > out/lie.rs
w4 png2src --rust lookup.png > out/lookup.rs
w4 png2src --rust jump.png > out/jump.rs
w4 png2src --rust walk0.png > out/walk0.rs
w4 png2src --rust walk1.png > out/walk1.rs
w4 png2src --rust walk2.png > out/walk2.rs
w4 png2src --rust walk3.png > out/walk3.rs
w4 png2src --rust climb.png > out/climb.rs
w4 png2src --rust board-right.png > out/board-right.rs
w4 png2src --rust board-up.png > out/board_up.rs
w4 png2src --rust tile.png > out/tile.rs