[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-A", "dead_code",


    # https://lld.llvm.org/WebAssembly.html

    # Import memory from WASM-4
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--initial-memory=65536",
    "-C", "link-arg=--max-memory=65536",

    # Temporary workaround for #255 issue.
    # Reserve 8192 bytes of Rust stack space, offset from 6560.
    # Bump this value, 16-byte aligned, if the framebuffer gets corrupted.
    "-C", "link-arg=-zstack-size=14752",

    # Not working? https://github.com/rust-lang/rust/issues/46645#issuecomment-423912553,

]
